apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7ImF1dGgiOiJkblJ6WlhCc2VXRjVaWFk2WjJod1gwOXdiSEpDZW1rd1MzRTRkVWhUYmtOUVJHODFORFJ2ZDJKNU9HNVpRVE15TUd4SU1RPT0ifX19
type: kubernetes.io/dockerconfigjson
