apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7ImF1dGgiOiJkblJ6WlhCc2VXRjVaWFk2WjJod1h6ZFRUVmxhTmxNME5XVXdNbE5IWVV4d1MxWnZZbUZ6U0ZGUGNreFJZVEp3Tm0wNGFBPT0ifX19
type: kubernetes.io/dockerconfigjson
